apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-service
spec:
  selector:
    app: hello-k8s
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31000  # Optional: Specify a fixed NodePort, or omit to let Kubernetes assign one
  type: NodePort

